name: Spirinity - Linux-x86 (GCC)

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install g++13, dependencies, and OpenGL headers
        run: |
          sudo apt update
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y g++-13 g++-13-multilib build-essential libgl1-mesa-dev libglu1-mesa-dev
          sudo apt install -y libgl1-mesa-dev:i386 libglu1-mesa-dev:i386
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Build
        run: sh linux/ci-make.sh g++13

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: |
            linux/release/client.so
            linux/release/client.so.dbg
            linux/release/spirit.so
            linux/release/spirit.so.dbg
