name: Spirinity - Linux-x86 (GCC)

on: [push, pull_request]

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: docker://registry.gitlab.steamos.cloud/steamrt/scout/sdk/i386:latest
        with:
          args: sh linux/ci-make.sh g++

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86
          path: |
            linux/release/client.so
            linux/release/client.so.dbg
            linux/release/spirit.so
            linux/release/spirit.so.dbg
